// src/stores/useSettingsStore.ts
import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'id' | 'en';
type Theme = 'dark' | 'light';

interface SettingsState {
  language: Language;
  theme: Theme;
  _hasHydrated: boolean;
  setLanguage: (lang: Language) => void;
  setTheme: (theme: Theme) => void;
  setHasHydrated: (state: boolean) => void;
}

export const useSettingsStore = create<SettingsState>()(
  persist(
    (set) => ({
      language: 'en',
      theme: 'dark',
      _hasHydrated: false,
      setLanguage: (lang) => set({ language: lang }),
      setTheme: (theme) => set({ theme }),
      setHasHydrated: (state) => set({ _hasHydrated: state }),
    }),
    {
      name: 'ash-settings-storage',
      storage: createJSONStorage(() => AsyncStorage),
      onRehydrateStorage: () => (state) => {
        state?.setHasHydrated(true);
      },
    }
  )
);

export const themes = {
  dark: {
    background: '#0f172a',
    card: '#1e293b',
    text: '#ffffff',
    textSecondary: '#94a3b8',
    primary: '#fbbf24',
    success: '#00ff88',
    error: '#ef4444',
    border: '#334155',
  },
  light: {
    background: '#f1f5f9',
    card: '#ffffff',
    text: '#1e293b',
    textSecondary: '#64748b',
    primary: '#f59e0b',
    success: '#10b981',
    error: '#ef4444',
    border: '#e2e8f0',
  }
} as const;

// ==========================================
// COMPREHENSIVE TRANSLATIONS (ID & EN)
// ==========================================

const id = {
  // Common
  loading: 'Memuat...',
  syncing: 'Menyinkronkan...',
  error: 'Kesalahan',
  success: 'Berhasil',
  cancel: 'Batal',
  save: 'Simpan',
  close: 'Tutup',
  ok: 'OK',
  confirm: 'Konfirmasi',
  back: 'Kembali',
  next: 'Lanjut',
  skip: 'Lewati',
  start: 'Mulai',
  stop: 'Berhenti',
  claim: 'Klaim',
  send: 'Kirim',
  receive: 'Terima',
  deposit: 'Deposit',
  withdraw: 'Tarik',
  copy: 'Salin',
  copied: 'Disalin!',

  // Auth
  login: 'Masuk',
  register: 'Daftar',
  email: 'Email',
  password: 'Kata Sandi',
  confirmPassword: 'Konfirmasi Kata Sandi',
  forgotPassword: 'Lupa Kata Sandi?',
  forgotPasswordTitle: 'Reset Kata Sandi',
  forgotPasswordDesc: 'Masukkan email Anda, kami akan mengirimkan link reset.',
  sendResetLink: 'Kirim Link Reset',
  resetLinkSent: 'Link reset telah dikirim ke email Anda.',
  loginSuccess: 'Login berhasil!',
  registerSuccess: 'Registrasi berhasil!',
  emailRequired: 'Email wajib diisi',
  passwordRequired: 'Kata sandi wajib diisi',
  passwordMinLength: 'Kata sandi minimal 6 karakter',
  passwordsNotMatch: 'Kata sandi tidak cocok',
  emailAlreadyUsed: 'Email sudah terdaftar. Silakan login.',
  invalidEmail: 'Format email tidak valid',
  weakPassword: 'Kata sandi terlalu lemah',
  networkError: 'Koneksi internet terputus',
  loginFailed: 'Login gagal',
  registerFailed: 'Registrasi gagal',
  alreadyHaveAccount: 'Sudah punya akun?',
  dontHaveAccount: 'Belum punya akun?',
  joinNow: 'GABUNG SEKARANG',
  startMiningJourney: 'Mulai Perjalanan Mining Anda',
  fullName: 'Nama Lengkap',
  referralCode: 'Kode Referral (Opsional)',
  referralHint: 'Kode referral dari link:',
  createAccount: 'BUAT AKUN',
  verificationEmailSent: 'Email verifikasi telah dikirim.',
  referrerCredited: 'Referrer mendapat 0.5 ASH!',

  // Dashboard
  welcomeBack: 'Selamat datang kembali,',
  miner: 'Penambang',
  totalBalance: 'Total Saldo',
  miningInProgress: 'MINING BERLANGSUNG',
  readyToMine: 'SIAP MINING',
  miningRate: 'Rate',
  startSession: 'MULAI SESI 6 JAM',
  stopSession: 'HENTIKAN SESI',
  claimRewards: 'KLAIM REWARD',
  stopMiningTitle: 'Hentikan Mining?',
  stopMiningDesc: 'Anda akan kehilangan reward yang belum diklaim.',
  dailyBonus: 'Bonus Harian',
  comeBackTomorrow: 'Kembali lagi besok!',
  guide: 'Panduan',
  wallet: 'Dompet',
  market: 'Pasar',

  // Mining
  miningSession6Hours: 'Sesi Mining (6 Jam)',
  miningAutoComplete: 'Mining otomatis selesai saat waktu habis. Klaim reward kapan saja!',
  boostEarnings: 'Tingkatkan Earning',
  watchAdBoost: 'Tonton iklan untuk aktifkan Standard Boost 30 menit (+50% hashrate), atau gunakan 14 ASH untuk Premium Boost 7 hari.',
  normal: 'Normal',
  boosted: '2x Boost',

  // Wallet
  availableBalance: 'Saldo Tersedia',
  kycRequired: 'KYC Diperlukan',
  kycRequiredDesc: 'Anda harus menyelesaikan verifikasi KYC untuk mengirim ASH.',
  insufficientBalance: 'Saldo Tidak Cukup',
  insufficientBalanceDesc: 'Anda tidak memiliki ASH yang cukup.',
  sendAsh: 'Kirim ASH',
  recipientAddress: 'Alamat Penerima / Kode Referral',
  recipientPlaceholder: 'Masukkan alamat atau kode referral',
  searching: 'Mencari...',
  recipientNotFound: 'Penerima tidak ditemukan',
  amount: 'Jumlah (ASH)',
  amountPlaceholder: '0.000000',
  gasFee: 'Gas Fee',
  totalCost: 'Total Biaya',
  available: 'Tersedia',
  remainingAfterSend: 'Sisa Setelah Kirim',
  confirmTransfer: 'KONFIRMASI TRANSFER',
  transferSuccessful: 'Transfer Berhasil',
  transferSent: 'Anda mengirim',
  invalidAmount: 'Jumlah Tidak Valid',
  invalidAmountDesc: 'Masukkan jumlah yang valid.',
  invalidAddress: 'Alamat Tidak Valid',
  invalidAddressDesc: 'Masukkan alamat atau kode referral yang valid.',
  recipientNotFoundTitle: 'Penerima Tidak Ditemukan',
  recipientNotFoundDesc: 'Tidak ada user dengan alamat atau kode referral tersebut.',
  cannotSelfTransfer: 'Tidak Valid',
  cannotSelfTransferDesc: 'Anda tidak bisa mengirim ASH ke diri sendiri.',
  transferFailed: 'Transfer gagal. Coba lagi.',
  yourUid: 'UID Anda',
  referralCodeLabel: 'Kode Referral',
  copyAddress: 'Salin Alamat',
  addressCopied: 'Alamat telah disalin ke clipboard.',
  stakingBalance: 'Saldo ASH Staking',
  availableInStaking: 'Tersedia di Aplikasi ASH Staking',
  transferToStaking: 'Transfer ke Staking',
  stakingLocked: 'Staking Terkunci',
  maxTransfer: 'Maks transfer',
  needToUnlock: 'Butuh',
  toUnlock: 'untuk membuka staking',
  miningBalance: 'Saldo Mining',
  stakingBalanceLabel: 'Saldo Staking',
  maxTransferLabel: 'Maks Transfer (1%)',
  amountToTransfer: 'Jumlah Transfer (ASH)',
  transferToStakingBtn: 'TRANSFER KE STAKING',
  transferFromStaking: 'Tarik dari Staking',
  amountToWithdraw: 'Jumlah Tarik (ASH)',
  transferFromStakingBtn: 'TARIK DARI STAKING',
  transferFromStakingSuccess: 'Berhasil ditarik dari Staking.',
  exceedsLimit: 'Melebihi Batas',
  exceedsLimitDesc: 'Maksimum transfer adalah',
  locked: 'Terkunci',
  lockedDesc: 'Anda perlu',
  toUnlockStaking: 'untuk membuka staking.',
  insufficientStakingBalance: 'Saldo staking tidak cukup.',

  // Profile
  account: 'AKUN',
  editName: 'Edit Nama & Username',
  nameLocked: 'Nama Terkunci',
  kycVerification: 'Verifikasi KYC',
  security: 'KEAMANAN',
  biometricLogin: 'Login Biometrik',
  faceIdFingerprint: 'FaceID / Sidik Jari',
  twoFactorAuth: 'Autentikasi 2 Faktor',
  enabled: 'Aktif',
  setupIncomplete: 'Setup belum lengkap',
  notConfigured: 'Belum dikonfigurasi',
  preferences: 'PREFERENSI',
  language: 'Bahasa',
  theme: 'Tema',
  darkTheme: 'Gelap',
  lightTheme: 'Terang',
  resources: 'SUMBER DAYA',
  officialWebsite: 'Website Resmi',
  whitepaper: 'Whitepaper',
  telegramCommunity: 'Komunitas Telegram',
  legal: 'LEGAL',
  privacyPolicy: 'Kebijakan Privasi',
  termsOfService: 'Syarat & Ketentuan',
  piNetworkUsername: 'Username Pi Network',
  notLinked: 'Belum dihubungkan',
  linkPiNetwork: 'Hubungkan Pi Network',
  piUsername: 'Username Pi',
  piUsernamePlaceholder: 'Masukkan username Pi Anda',
  piUsernameSaved: 'Pi Username berhasil dihubungkan.',
  piUsernameFailed: 'Gagal menyimpan Pi Username.',
  tapAvatar: 'Tap avatar untuk ganti foto',
  permissionRequired: 'Izin Diperlukan',
  permissionRequiredDesc: 'Izinkan akses galeri untuk upload foto.',
  photoUploadSuccess: 'Foto profil berhasil diupdate.',
  photoUploadFailed: 'Gagal upload foto. Coba lagi.',
  nameSaved: 'Nama berhasil diubah.',
  nameSaveFailed: 'Gagal menyimpan nama.',
  logout: 'Keluar',
  logoutTitle: 'Keluar',
  logoutDesc: 'Yakin mau keluar?',
  logoutFailed: 'Gagal logout.',
  setup2FA: 'Setup 2FA',
  verifyAtLeastOne: 'Verifikasi minimal satu metode untuk mengaktifkan 2FA.',
  emailVerification: 'Verifikasi Email',
  verified: 'Terverifikasi',
  check: 'Cek',
  sentTo: 'Dikirim ke:',
  sendVerificationLink: 'Kirim Link Verifikasi',
  iveVerified: 'Sudah Verifikasi - Cek Status',
  emailSent: 'Email Terkirim',
  emailSentDesc: 'Link verifikasi dikirim ke',
  checkInbox: 'Cek inbox atau folder spam Anda.',
  emailSendFailed: 'Gagal mengirim email verifikasi.',
  notVerifiedYet: 'Belum Terverifikasi',
  notVerifiedYetDesc: 'Klik link di email Anda terlebih dahulu, lalu coba lagi.',
  verificationCheckFailed: 'Gagal cek status verifikasi.',
  phoneVerification: 'Verifikasi Telepon',
  phonePlaceholder: '+62 812 xxxx xxxx',
  sendOtp: 'Kirim Kode OTP',
  otpSent: 'OTP Terkirim',
  otpSentDesc: 'OTP dikirim ke',
  otpEnterDesc: 'Masukkan kode 6 digit.',
  enterOtp: 'Masukkan OTP 6 digit',
  verifyOtp: 'Verifikasi OTP',
  resendOtp: 'Kirim Ulang OTP',
  invalidPhone: 'Tidak Valid',
  invalidPhoneDesc: 'Masukkan nomor telepon yang valid.',
  otpSendFailed: 'Gagal mengirim OTP.',
  wrongCode: 'Kode Salah',
  wrongCodeDesc: 'Kode verifikasi tidak cocok.',
  phoneVerified: 'Telepon terverifikasi! 2FA telah diaktifkan.',
  otpVerifyFailed: 'Gagal verifikasi OTP.',
  emailVerified: 'Email terverifikasi! 2FA telah diaktifkan.',
  twoFAActive: '2FA Aktif',
  twoFAActiveDesc: 'Akun Anda dilindungi dengan 2FA.',

  // Market
  liveCryptoData: 'Data Crypto Langsung',
  ashPrice: 'Harga ASH (USD)',
  topCryptos: 'Crypto Teratas',
  ashEcosystem: 'Ekosistem ASH',
  ashStakingApp: 'Aplikasi ASH Staking',
  openWebApp: 'Buka Web App',
  ashP2P: 'ASH P2P',
  ashBlaze: 'ASH BLAZE',
  inDevelopment: 'Dalam Pengembangan',
  latestNews: 'Berita Terbaru',
  loadingMarketData: 'MEMUAT DATA PASAR...',
  marketLoadError: 'Gagal memuat data pasar. Cek koneksi internet.',

  // Team / Syndicate
  syndicate: 'SINDIKAT',
  buildYourNetwork: 'Bangun Jaringan Anda',
  rank: 'PANGKAT',
  totalMembers: 'Total Anggota',
  activeMiners: 'Penambang Aktif',
  commissionEarned: 'Komisi Didapat',
  inviteCode: 'Kode Undangan',
  shareInviteLink: 'BAGIKAN LINK UNDANGAN',
  liveCommission: 'Komisi Langsung',
  commissionDesc: 'Anda mendapat 5% dari reward mining harian tim Anda.',
  yourNetwork: 'Jaringan Anda',
  noMembers: 'Belum ada anggota. Undang teman!',
  inviteFriends: 'Undang teman!',
  miningActive: 'Mining Aktif',
  idle: 'Idle',
  active: 'Aktif',
  copiedCode: 'Disalin!',
  copiedCodeDesc: 'Kode',
  copiedToClipboard: 'disalin ke clipboard',
  shareFailed: 'Gagal membagikan.',

  // KYC
  kycTitle: 'Verifikasi KYC',
  fullNameLabel: 'Nama Lengkap',
  fullNamePlaceholder: 'John Doe',
  address: 'Alamat',
  addressPlaceholder: 'Jl. Sudirman No. 1...',
  idNumber: 'Nomor KTP/Paspor',
  idNumberPlaceholder: '1234567890',
  uploadIdPhoto: 'Upload Foto KTP',
  chooseSource: 'Pilih sumber:',
  takePhoto: 'Ambil Foto',
  chooseGallery: 'Pilih dari Galeri',
  tapToUpload: 'Tap untuk Upload',
  incomplete: 'Belum Lengkap',
  incompleteDesc: 'Isi semua field dan upload foto KTP.',
  kycSubmitted: 'KYC berhasil dikirim untuk review.',
  kycNotification: 'Anda akan diberi tahu setelah disetujui.',
  kycSubmitFailed: 'Gagal mengirim KYC. Coba lagi.',

  // Onboarding
  onboardingWelcome: 'Selamat Datang di ASH Protocol',
  onboardingWelcomeDesc: 'Mulai earning ASH coins melalui mining. Setiap tap dihitung — perjalananmu menuju kebebasan finansial dimulai di sini!',
  onboardingMining: 'Sesi Mining (6 Jam)',
  onboardingMiningDesc: 'Mulai sesi mining dan dapatkan ASH selama 6 jam. Mining otomatis selesai saat waktu habis. Klaim rewards kapan saja!',
  onboardingBoost: 'Tingkatkan Earning',
  onboardingBoostDesc: 'Tonton iklan untuk aktifkan Standard Boost 30 menit (+50% hashrate), atau gunakan 14 ASH untuk Premium Boost 7 hari.',
  onboardingDaily: 'Bonus Harian',
  onboardingDailyDesc: 'Klaim bonus gratis 0.005 ASH setiap hari. Tinggal tap tombol Gift hijau di Dashboard!',
  onboardingInvite: 'Undang & Dapatkan',
  onboardingInviteDesc: 'Bagikan kode referral kamu ke teman. Saat mereka daftar pakai kode kamu, kalian berdua dapat bonus!',
  onboardingSendReceive: 'Kirim & Terima ASH',
  onboardingSendReceiveDesc: 'Setelah verifikasi KYC, kamu bisa kirim ASH ke user lain dengan gas fee kecil (0.001 ASH). Murah & cepat!',
  onboardingSecurity: 'Amankan Akunmu',
  onboardingSecurityDesc: 'Aktifkan Biometric Login dan 2FA di pengaturan Profil untuk menjaga ASH kamu dari akses yang tidak sah.',
  onboardingEcosystem: 'Ekosistem ASH',
  onboardingEcosystemDesc: 'Jelajahi ASH Staking, trading P2P, dan fitur lainnya yang segera hadir. ASH kamu bertumbuh seiring ekosistem!',
  startMining: 'Mulai Mining!',
  continue: 'Lanjut',

  // Pi Network
  connectPiNetwork: 'Hubungkan Pi Network',
  bridgeAssets: 'Bridge aset via Pi Browser',
  piConnected: 'Pi Terhubung',
  piConnectedDesc: 'Anda sedang berjalan di dalam Pi Browser.',
  piBrowserNotFound: 'Pi Browser Tidak Ditemukan',
  piBrowserNotFoundDesc: 'Install Pi Browser dari Play Store/App Store untuk terhubung.',

  // Errors
  systemError: 'Terjadi kesalahan sistem.',
  tryAgain: 'Coba lagi.',
  noInternet: 'Tidak ada koneksi internet.',
  sessionExpired: 'Sesi berakhir. Silakan login ulang.',
};

const en: Record<keyof typeof id, string> = {
  // Common
  loading: 'Loading...',
  syncing: 'Synchronizing...',
  error: 'Error',
  success: 'Success',
  cancel: 'Cancel',
  save: 'Save',
  close: 'Close',
  ok: 'OK',
  confirm: 'Confirm',
  back: 'Back',
  next: 'Next',
  skip: 'Skip',
  start: 'Start',
  stop: 'Stop',
  claim: 'Claim',
  send: 'Send',
  receive: 'Receive',
  deposit: 'Deposit',
  withdraw: 'Withdraw',
  copy: 'Copy',
  copied: 'Copied!',

  // Auth
  login: 'Login',
  register: 'Register',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  forgotPassword: 'Forgot Password?',
  forgotPasswordTitle: 'Reset Password',
  forgotPasswordDesc: 'Enter your email, we will send you a reset link.',
  sendResetLink: 'Send Reset Link',
  resetLinkSent: 'Reset link has been sent to your email.',
  loginSuccess: 'Login successful!',
  registerSuccess: 'Registration successful!',
  emailRequired: 'Email is required',
  passwordRequired: 'Password is required',
  passwordMinLength: 'Password must be at least 6 characters',
  passwordsNotMatch: 'Passwords do not match',
  emailAlreadyUsed: 'Email already registered. Please login.',
  invalidEmail: 'Invalid email format',
  weakPassword: 'Password is too weak',
  networkError: 'Network connection lost',
  loginFailed: 'Login failed',
  registerFailed: 'Registration failed',
  alreadyHaveAccount: 'Already have an account?',
  dontHaveAccount: "Don't have an account?",
  joinNow: 'JOIN NOW',
  startMiningJourney: 'Start Your Mining Journey',
  fullName: 'Full Name',
  referralCode: 'Referral Code (Optional)',
  referralHint: 'Referral code from link:',
  createAccount: 'CREATE ACCOUNT',
  verificationEmailSent: 'Verification email has been sent.',
  referrerCredited: 'Referrer credited 0.5 ASH!',

  // Dashboard
  welcomeBack: 'Welcome back,',
  miner: 'Miner',
  totalBalance: 'Total Balance',
  miningInProgress: 'MINING IN PROGRESS',
  readyToMine: 'READY TO MINE',
  miningRate: 'Rate',
  startSession: 'START 6H SESSION',
  stopSession: 'STOP SESSION',
  claimRewards: 'CLAIM REWARDS',
  stopMiningTitle: 'Stop Mining?',
  stopMiningDesc: 'You will lose unclaimed session rewards.',
  dailyBonus: 'Daily Bonus',
  comeBackTomorrow: 'Come back tomorrow!',
  guide: 'Guide',
  wallet: 'Wallet',
  market: 'Market',

  // Mining
  miningSession6Hours: 'Mining Sessions (6 Hours)',
  miningAutoComplete: 'Mining auto-completes when time is up. Claim rewards anytime!',
  boostEarnings: 'Boost Your Earnings',
  watchAdBoost: 'Watch an ad to activate a 30-min Standard Boost (+50% hashrate), or use 14 ASH for a 7-day Premium Boost.',
  normal: 'Normal',
  boosted: '2x Boost',

  // Wallet
  availableBalance: 'Available Balance',
  kycRequired: 'KYC Required',
  kycRequiredDesc: 'You must complete KYC verification to send ASH.',
  insufficientBalance: 'Insufficient Balance',
  insufficientBalanceDesc: 'You do not have enough ASH.',
  sendAsh: 'Send ASH',
  recipientAddress: 'Recipient Address / Referral Code',
  recipientPlaceholder: 'Enter address or referral code',
  searching: 'Searching...',
  recipientNotFound: 'Recipient not found',
  amount: 'Amount (ASH)',
  amountPlaceholder: '0.000000',
  gasFee: 'Gas Fee',
  totalCost: 'Total Cost',
  available: 'Available',
  remainingAfterSend: 'Remaining After Send',
  confirmTransfer: 'CONFIRM TRANSFER',
  transferSuccessful: 'Transfer Successful',
  transferSent: 'You sent',
  invalidAmount: 'Invalid Amount',
  invalidAmountDesc: 'Please enter a valid amount.',
  invalidAddress: 'Invalid Address',
  invalidAddressDesc: 'Please enter a valid recipient address or referral code.',
  recipientNotFoundTitle: 'Recipient Not Found',
  recipientNotFoundDesc: 'No user found with that address or referral code.',
  cannotSelfTransfer: 'Invalid',
  cannotSelfTransferDesc: 'You cannot send ASH to yourself.',
  transferFailed: 'Transfer failed. Please try again.',
  yourUid: 'Your UID',
  referralCodeLabel: 'Referral Code',
  copyAddress: 'Copy Address',
  addressCopied: 'Your address has been copied to clipboard.',
  stakingBalance: 'ASH Staking Balance',
  availableInStaking: 'Available in ASH Staking App',
  transferToStaking: 'Transfer to Staking',
  stakingLocked: 'Staking Locked',
  maxTransfer: 'Max transfer',
  needToUnlock: 'Need',
  toUnlock: 'to unlock staking',
  miningBalance: 'Mining Balance',
  stakingBalanceLabel: 'Staking Balance',
  maxTransferLabel: 'Max Transfer (1%)',
  amountToTransfer: 'Amount to Transfer (ASH)',
  transferToStakingBtn: 'TRANSFER TO STAKING',
  transferFromStaking: 'Withdraw from Staking',
  amountToWithdraw: 'Amount to Withdraw (ASH)',
  transferFromStakingBtn: 'WITHDRAW FROM STAKING',
  transferFromStakingSuccess: 'Successfully withdrawn from Staking.',
  exceedsLimit: 'Exceeds Limit',
  exceedsLimitDesc: 'Maximum transfer is',
  locked: 'Locked',
  lockedDesc: 'You need',
  toUnlockStaking: 'to unlock staking.',
  insufficientStakingBalance: 'Insufficient staking balance.',

  // Profile
  account: 'ACCOUNT',
  editName: 'Edit Name & Username',
  nameLocked: 'Name Locked',
  kycVerification: 'KYC Verification',
  security: 'SECURITY',
  biometricLogin: 'Biometric Login',
  faceIdFingerprint: 'FaceID / Fingerprint',
  twoFactorAuth: '2-Factor Auth',
  enabled: 'Enabled',
  setupIncomplete: 'Setup incomplete',
  notConfigured: 'Not configured',
  preferences: 'PREFERENCES',
  language: 'Language',
  theme: 'Theme',
  darkTheme: 'Dark',
  lightTheme: 'Light',
  resources: 'RESOURCES',
  officialWebsite: 'Official Website',
  whitepaper: 'Whitepaper',
  telegramCommunity: 'Telegram Community',
  legal: 'LEGAL',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  piNetworkUsername: 'Pi Network Username',
  notLinked: 'Not linked',
  linkPiNetwork: 'Link Pi Network',
  piUsername: 'Pi Username',
  piUsernamePlaceholder: 'Enter your Pi username',
  piUsernameSaved: 'Pi Username successfully linked.',
  piUsernameFailed: 'Failed to save Pi Username.',
  tapAvatar: 'Tap avatar to change photo',
  permissionRequired: 'Permission Required',
  permissionRequiredDesc: 'Allow gallery access to upload photo.',
  photoUploadSuccess: 'Profile photo updated successfully.',
  photoUploadFailed: 'Failed to upload photo. Try again.',
  nameSaved: 'Name changed successfully.',
  nameSaveFailed: 'Failed to save name.',
  logout: 'Logout',
  logoutTitle: 'Logout',
  logoutDesc: 'Are you sure you want to logout?',
  logoutFailed: 'Failed to logout.',
  setup2FA: 'Setup 2FA',
  verifyAtLeastOne: 'Verify at least one method to enable 2FA.',
  emailVerification: 'Email Verification',
  verified: 'Verified',
  check: 'Check',
  sentTo: 'Sent to:',
  sendVerificationLink: 'Send Verification Link',
  iveVerified: "I've Verified - Check Status",
  emailSent: 'Email Sent',
  emailSentDesc: 'Verification link sent to',
  checkInbox: 'Check your inbox or spam folder.',
  emailSendFailed: 'Failed to send verification email.',
  notVerifiedYet: 'Not Verified Yet',
  notVerifiedYetDesc: 'Please click the link in your email first, then try again.',
  verificationCheckFailed: 'Failed to check verification status.',
  phoneVerification: 'Phone Verification',
  phonePlaceholder: '+62 812 xxxx xxxx',
  sendOtp: 'Send OTP Code',
  otpSent: 'OTP Sent',
  otpSentDesc: 'OTP sent to',
  otpEnterDesc: 'Enter the 6-digit code.',
  enterOtp: 'Enter 6-digit OTP',
  verifyOtp: 'Verify OTP',
  resendOtp: 'Resend OTP',
  invalidPhone: 'Invalid',
  invalidPhoneDesc: 'Please enter a valid phone number.',
  otpSendFailed: 'Failed to send OTP.',
  wrongCode: 'Wrong Code',
  wrongCodeDesc: 'The verification code does not match.',
  phoneVerified: 'Phone verified! 2FA has been enabled.',
  otpVerifyFailed: 'Failed to verify OTP.',
  emailVerified: 'Email verified! 2FA has been enabled.',
  twoFAActive: '2FA Active',
  twoFAActiveDesc: 'Your account is protected with 2FA.',

  // Market
  liveCryptoData: 'Live Crypto Data',
  ashPrice: 'ASH Price (USD)',
  topCryptos: 'Top Cryptos',
  ashEcosystem: 'ASH Ecosystem',
  ashStakingApp: 'ASH Staking App',
  openWebApp: 'Open Web App',
  ashP2P: 'ASH P2P',
  ashBlaze: 'ASH BLAZE',
  inDevelopment: 'In Development',
  latestNews: 'Latest News',
  loadingMarketData: 'LOADING MARKET DATA...',
  marketLoadError: 'Failed to load market data. Check your internet connection.',

  // Team / Syndicate
  syndicate: 'SYNDICATE',
  buildYourNetwork: 'Build Your Network',
  rank: 'RANK',
  totalMembers: 'Total Members',
  activeMiners: 'Active Miners',
  commissionEarned: 'Comm. Earned',
  inviteCode: 'Invite Code',
  shareInviteLink: 'SHARE INVITE LINK',
  liveCommission: 'Live Commission',
  commissionDesc: 'You earn 5% of your team\'s daily mining rewards.',
  yourNetwork: 'Your Network',
  noMembers: 'No members yet. Invite friends!',
  inviteFriends: 'Invite friends!',
  miningActive: 'Mining Active',
  idle: 'Idle',
  active: 'Active',
  copiedCode: 'Copied!',
  copiedCodeDesc: 'Code',
  copiedToClipboard: 'copied to clipboard',
  shareFailed: 'Failed to share.',

  // KYC
  kycTitle: 'KYC Verification',
  fullNameLabel: 'Full Name',
  fullNamePlaceholder: 'John Doe',
  address: 'Address',
  addressPlaceholder: 'Jl. Sudirman No. 1...',
  idNumber: 'ID Number (KTP/Passport)',
  idNumberPlaceholder: '1234567890',
  uploadIdPhoto: 'Upload ID Photo',
  chooseSource: 'Choose source:',
  takePhoto: 'Take Photo',
  chooseGallery: 'Choose from Gallery',
  tapToUpload: 'Tap to Upload',
  incomplete: 'Incomplete',
  incompleteDesc: 'Please fill all fields and upload ID photo.',
  kycSubmitted: 'KYC submitted for review.',
  kycNotification: 'You will be notified once approved.',
  kycSubmitFailed: 'Failed to submit KYC. Please try again.',

  // Onboarding
  onboardingWelcome: 'Welcome to ASH Protocol',
  onboardingWelcomeDesc: 'Start earning ASH coins through mining. Every tap counts — your journey to financial freedom begins here!',
  onboardingMining: 'Mining Sessions (6 Hours)',
  onboardingMiningDesc: 'Start a mining session and earn ASH over 6 hours. Mining auto-completes when time is up. Claim your rewards anytime!',
  onboardingBoost: 'Boost Your Earnings',
  onboardingBoostDesc: 'Watch an ad to activate a 30-min Standard Boost (+50% hashrate), or use 14 ASH for a 7-day Premium Boost.',
  onboardingDaily: 'Daily Bonus',
  onboardingDailyDesc: 'Claim your free 0.005 ASH bonus every day. Just tap the green Gift button on the Dashboard!',
  onboardingInvite: 'Invite & Earn',
  onboardingInviteDesc: 'Share your referral code with friends. When they join using your code, you both get bonuses!',
  onboardingSendReceive: 'Send & Receive ASH',
  onboardingSendReceiveDesc: 'After KYC verification, you can send ASH to other users with a tiny gas fee (0.001 ASH). Cheap & fast!',
  onboardingSecurity: 'Secure Your Account',
  onboardingSecurityDesc: 'Enable Biometric Login and 2FA in your Profile settings to keep your ASH safe from unauthorized access.',
  onboardingEcosystem: 'ASH Ecosystem',
  onboardingEcosystemDesc: 'Explore ASH Staking, P2P trading, and more coming soon. Your ASH grows in value with the ecosystem!',
  startMining: 'Start Mining!',
  continue: 'Next',

  // Pi Network
  connectPiNetwork: 'Connect Pi Network',
  bridgeAssets: 'Bridge assets via Pi Browser',
  piConnected: 'Pi Connected',
  piConnectedDesc: 'You are running inside Pi Browser.',
  piBrowserNotFound: 'Pi Browser Not Found',
  piBrowserNotFoundDesc: 'Please install Pi Browser from Play Store/App Store to connect.',

  // Errors
  systemError: 'A system error occurred.',
  tryAgain: 'Try again.',
  noInternet: 'No internet connection.',
  sessionExpired: 'Session expired. Please login again.',
};

export const translations = { id, en };
export type TranslationKeys = keyof typeof id;
